<script>
  import SectionHeading from '$lib/components/SectionHeading.svelte';
</script>

<div id="social-section">
  <SectionHeading>
    Partnerships
  </SectionHeading>

  <div class="
    mb-8
    text-secondaryText
  ">
    <p class="
      mb-2
    ">
      <!-- TODO -->
    </p>
  </div>

  <div
    id="embeds"
    class="text-text"
  >
    <blockquote class="tiktok-embed" cite="https://www.tiktok.com/@mallory_rosey" data-unique-id="mallory_rosey" data-embed-type="creator" style="max-width: 780px; min-width: 288px;" > <section> <a target="_blank" href="https://www.tiktok.com/@mallory_rosey?refer=creator_embed">@mallory_rosey</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>
    
    <blockquote class="tiktok-embed" cite="https://www.tiktok.com/@mallory_rosey/video/7090740489032305963" data-video-id="7090740489032305963" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@mallory_rosey" href="https://www.tiktok.com/@mallory_rosey?refer=embed">@mallory_rosey</a> SO YUMMY! <a title="springroll" target="_blank" href="https://www.tiktok.com/tag/springroll?refer=embed">#springroll</a> <a title="madisonwi" target="_blank" href="https://www.tiktok.com/tag/madisonwi?refer=embed">#madisonwi</a> <a title="uwmadison" target="_blank" href="https://www.tiktok.com/tag/uwmadison?refer=embed">#uwmadison</a> <a title="smoothie" target="_blank" href="https://www.tiktok.com/tag/smoothie?refer=embed">#smoothie</a> <a title="foodtruck" target="_blank" href="https://www.tiktok.com/tag/foodtruck?refer=embed">#foodtruck</a> <a title="wisconsin" target="_blank" href="https://www.tiktok.com/tag/wisconsin?refer=embed">#wisconsin</a> <a title="wisconsinfoodie" target="_blank" href="https://www.tiktok.com/tag/wisconsinfoodie?refer=embed">#wisconsinfoodie</a> <a title="foodie" target="_blank" href="https://www.tiktok.com/tag/foodie?refer=embed">#foodie</a> <a title="wisconsinfoodies" target="_blank" href="https://www.tiktok.com/tag/wisconsinfoodies?refer=embed">#wisconsinfoodies</a> <a title="totinos425" target="_blank" href="https://www.tiktok.com/tag/totinos425?refer=embed">#Totinos425</a> <a title="onlyinmycalvins" target="_blank" href="https://www.tiktok.com/tag/onlyinmycalvins?refer=embed">#onlyinmycalvins</a> <a title="pringlescanhands" target="_blank" href="https://www.tiktok.com/tag/pringlescanhands?refer=embed">#PringlesCanHands</a> <a title="healthyliving" target="_blank" href="https://www.tiktok.com/tag/healthyliving?refer=embed">#healthyliving</a> <a title="healthyeating" target="_blank" href="https://www.tiktok.com/tag/healthyeating?refer=embed">#healthyeating</a> <a target="_blank" title="♬ Campus - Vampire Weekend" href="https://www.tiktok.com/music/Campus-6901092050247469829?refer=embed">♬ Campus - Vampire Weekend</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>
    
    <blockquote class="tiktok-embed" cite="https://www.tiktok.com/@mallory_rosey/video/7095910588328480043" data-video-id="7095910588328480043" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@mallory_rosey" href="https://www.tiktok.com/@mallory_rosey?refer=embed">@mallory_rosey</a> We love <a title="eatinglocal" target="_blank" href="https://www.tiktok.com/tag/eatinglocal?refer=embed">#eatinglocal</a> 💓 this is Parthenon Gyros in Madison, WI, right on State Street <a title="madisonwi" target="_blank" href="https://www.tiktok.com/tag/madisonwi?refer=embed">#madisonwi</a> <a title="madison" target="_blank" href="https://www.tiktok.com/tag/madison?refer=embed">#madison</a> <a title="wisconsin" target="_blank" href="https://www.tiktok.com/tag/wisconsin?refer=embed">#wisconsin</a> <a title="wisconsinfoodie" target="_blank" href="https://www.tiktok.com/tag/wisconsinfoodie?refer=embed">#wisconsinfoodie</a> <a title="wisconsinfoodies" target="_blank" href="https://www.tiktok.com/tag/wisconsinfoodies?refer=embed">#wisconsinfoodies</a> <a title="foodie" target="_blank" href="https://www.tiktok.com/tag/foodie?refer=embed">#foodie</a> <a title="gyro" target="_blank" href="https://www.tiktok.com/tag/gyro?refer=embed">#gyro</a> <a title="gyros" target="_blank" href="https://www.tiktok.com/tag/gyros?refer=embed">#gyros</a> <a title="greek" target="_blank" href="https://www.tiktok.com/tag/greek?refer=embed">#greek</a> <a title="greekfood" target="_blank" href="https://www.tiktok.com/tag/greekfood?refer=embed">#greekfood</a> <a title="healthyfood" target="_blank" href="https://www.tiktok.com/tag/healthyfood?refer=embed">#healthyfood</a> <a title="fordforthebuilders" target="_blank" href="https://www.tiktok.com/tag/fordforthebuilders?refer=embed">#FORDfortheBuilders</a> <a title="foodies" target="_blank" href="https://www.tiktok.com/tag/foodies?refer=embed">#foodies</a> <a title="healthyeating" target="_blank" href="https://www.tiktok.com/tag/healthyeating?refer=embed">#healthyeating</a> @parthenongyros <a target="_blank" title="♬ original sound - ansley" href="https://www.tiktok.com/music/original-sound-7036953803337452334?refer=embed">♬ original sound - ansley</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>
    
    <blockquote class="tiktok-embed" cite="https://www.tiktok.com/@mallory_rosey/video/7117462639344717098" data-video-id="7117462639344717098" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@mallory_rosey" href="https://www.tiktok.com/@mallory_rosey?refer=embed">@mallory_rosey</a> Beat Kitchen in Chicago, IL 📍 <a title="riverwalk" target="_blank" href="https://www.tiktok.com/tag/riverwalk?refer=embed">#riverwalk</a> <a title="riverwalkchicago" target="_blank" href="https://www.tiktok.com/tag/riverwalkchicago?refer=embed">#riverwalkchicago</a> <a title="chicago" target="_blank" href="https://www.tiktok.com/tag/chicago?refer=embed">#chicago</a> <a title="chicagoillinois" target="_blank" href="https://www.tiktok.com/tag/chicagoillinois?refer=embed">#chicagoillinois</a> <a title="happyhour" target="_blank" href="https://www.tiktok.com/tag/happyhour?refer=embed">#happyhour</a> <a title="chicagofood" target="_blank" href="https://www.tiktok.com/tag/chicagofood?refer=embed">#chicagofood</a> <a title="chicagofoodie" target="_blank" href="https://www.tiktok.com/tag/chicagofoodie?refer=embed">#chicagofoodie</a> <a title="chicagofoodies" target="_blank" href="https://www.tiktok.com/tag/chicagofoodies?refer=embed">#chicagofoodies</a> <a title="chicagofoodguide" target="_blank" href="https://www.tiktok.com/tag/chicagofoodguide?refer=embed">#chicagofoodguide</a> <a target="_blank" title="♬ original sound - Ian Asher" href="https://www.tiktok.com/music/original-sound-7052810772242205486?refer=embed">♬ original sound - Ian Asher</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>
    
    <blockquote class="tiktok-embed" cite="https://www.tiktok.com/@mallory_rosey/video/7232088577172180266" data-video-id="7232088577172180266" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@mallory_rosey" href="https://www.tiktok.com/@mallory_rosey?refer=embed">@mallory_rosey</a> Lazy Sunday mornings 💕 <a title="chicago" target="_blank" href="https://www.tiktok.com/tag/chicago?refer=embed">#chicago</a> <a title="downtownchicago" target="_blank" href="https://www.tiktok.com/tag/downtownchicago?refer=embed">#downtownchicago</a> <a title="midwestfoodie" target="_blank" href="https://www.tiktok.com/tag/midwestfoodie?refer=embed">#midwestfoodie</a> <a title="chicagofoodie" target="_blank" href="https://www.tiktok.com/tag/chicagofoodie?refer=embed">#chicagofoodie</a> <a title="sunday" target="_blank" href="https://www.tiktok.com/tag/sunday?refer=embed">#sunday</a> <a title="sundayfunday" target="_blank" href="https://www.tiktok.com/tag/sundayfunday?refer=embed">#sundayfunday</a> <a target="_blank" title="♬ Never Let You Go (2006 Remaster) - Third Eye Blind" href="https://www.tiktok.com/music/Never-Let-You-Go-2006-Remaster-6705070492522383361?refer=embed">♬ Never Let You Go (2006 Remaster) - Third Eye Blind</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>
  </div>
</div>
